import enum


class ReviewFeedbackEnum(str, enum.Enum):
    NOT_READ = "NOT_READ"
    PARTIALLY_UNDERSTOOD = "PARTIALLY_UNDERSTOOD"
    UNDERSTOOD = "UNDERSTOOD"
    WELL_UNDERSTOOD = "WELL_UNDERSTOOD"
    NEEDS_REVISIT = "NEEDS_REVISIT"
    CRITICAL_FOR_PHD = "CRITICAL_FOR_PHD"
